# Generated by Django 4.1.2 on 2022-10-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_aluno_dicas_professor_delete_article_dicas_professor"),
    ]

    operations = [
        migrations.RemoveField(model_name="dicas", name="professor",),
    ]
